### ISSUE TITLE
breeding unkown. 'buggies' feel

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#10]
# breeding unkown. 'buggies' feel

tried to hop 2 of my own pepe; 75 and 103. 
Did metamask accept.. waited.. nothing. gui removed "cosy plans"
went to "can hop" tab. pepe 103 was there. pepe 75 was not. went to cooldown. nothing.
a few minutes later pepe 150 appeared. and pepe75 re-appeared on "can hop" 

I was not sure what happend. Maybe some clear "pending" or "hopping succesfull" messages? 

### Affected parts

- [x] Backend API: search/lookups
- [x] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [x] Smartcontracts - miscellaneous
- [ ] Miscellaneous

### Accounts used

Transaction.
https://ropsten.etherscan.io/tx/0x70d0ba9548d1318f25252d04d34cc76de73f1e265a72f3cc5c1daec7a5a56d21

acc: 0x892b85B5a6412e12E749A94D3e0b9fe519C4a032

### Common questions

> Check the boxes that apply

- [x] Logged in?
- [ ] Recently switched accounts?
- [ ] Do you use multiple accounts at the same time?

> Answer briefly, if relevant

**Which Web3 wallet do you use?**

Metamask,

**Comment by programmerror** [comment]
Seeing this as part of a larger issue, so I created #30. You can continue discussion there if you want. Closing this issue now.
