### ISSUE TITLE
User feedback when selling pepe on auction

### ISSUE THREAD

**Issue by crmn111** [CryptoPepes/cryptopepes-alpha-test#13]
After pressing submit on sell pepe on auction dialogue, you see the message:
'Start Sale Auction Broadcasting ....'

It is not really noticeable and doesn't give the impression to the user that it was successful.

Perhaps animate dots after broadcasting to show that something is happening and/or give a success message.

<img width="647" alt="screen shot 2018-06-12 at 12 06 25" src="https://user-images.githubusercontent.com/881181/41286530-22cdc016-6e40-11e8-9562-a9ddece5304a.png">

**Comment by programmerror** [comment]
Seeing this as part of a larger issue, so I created #30. You can continue discussion there if you want. Closing this issue now.
