### ISSUE TITLE
Auto update after action?

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#14]
# Auto update after action?

Pepe page are not updating after selling or renaming ect.
You have to press F5 to see if anything happend. 
There is no message or popup or status. 
this also allows for the user to rename or auction a pepe thats already on the sale list. this may cause the user to lose money for transactions that are unavaible. 

### Affected parts

- [x] *example checked item*
- [ ] Backend API: search/lookups
- [x] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [x] Miscellaneous

### Steps to reproduce

1. do something with your pepe
2. accept transaction
3. nothing changes visually.

**Comment by programmerror** [comment]
Seeing this as part of a larger issue, so I created #30. You can continue discussion there if you want. Closing this issue now.
