### ISSUE TITLE
Seller of my pepe is "Anon pepe trader (no username)"

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#15]
# Seller of my pepe is "Anon pepe trader (no username)"

Seller of my pepe is "Anon pepe trader (no username)".  @ 0x1086c166eF05fB94A969696Aae491CdB22ECc316

but my account is: 
0x892b85B5a6412e12E749A94D3e0b9fe519C4a032

### Affected parts

- [x] Backend API: search/lookups
- [x] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [x] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [x] Miscellaneous

### Steps to reproduce

1. sell pepe
2. look at pepe page.

**Comment by programmerror** [comment]
That's the address of the auction contract. Technically, it's the seller. But I see why you'd expect your own address to show up. Good feedback :+1:

**Comment by programmerror** [comment]
fixed in next release
