### ISSUE TITLE
Select pepe property text not visable in dark theme

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#16]
# Select pepe property text not visable in dark theme

![image](https://user-images.githubusercontent.com/7458738/41286934-6c749298-6e41-11e8-911a-67ff42ca48f6.png)

 using chrome on windows 10.

**Comment by Twente-Mining** [comment]
same for me

**Comment by programmerror** [comment]
Yup, that's a problem with the native selection dropdown, I will see if the background color can be changed to black, so that the white text is visible. We can make switch to either a non-native select, or black text. Does anyone have a preference? @Twente-Mining @rayhvh

**Comment by Twente-Mining** [comment]
dark background in the bar is best in my opinion.

**Comment by programmerror** [comment]
Hmm, looks like browsers don't respect styling inputs well or consistent between platforms. I'm switching it to non-native selector, that should work better.

**Comment by programmerror** [comment]
fixed in next release
