### ISSUE TITLE
Share icon/button does nothing

### ISSUE THREAD

**Issue by kitblake** [CryptoPepes/cryptopepes-alpha-test#17]
# Share icon/button does nothing

In *Marketplace* each Pepe has a Share icon but it's not yet functional. 

### Affected parts

- [ ] Backend API: search/lookups
- [x] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [ ] Miscellaneous

### Accounts used

> Please name the accounts used, for better communication.

```
Main: 0xEcFf9b352fbb9A59aEAe10D6DAd636e6f07a0570
```

### Common questions

> Check the boxes that apply

- [x] Logged in?
- [x] Recently switched accounts?
- [ ] Do you use multiple accounts at the same time?

**Which Web3 wallet do you use?**

Metamask

**Comment by programmerror** [comment]
Not really a bug, just hasn't been implemented yet, it's a placeholder. Thanks for the report however, we'll fix it.

**Comment by programmerror** [comment]
Removed it for now, it may come back later, during final polishing of the game
