### ISSUE TITLE
Both sell and cosy time auction are "Start sale auction: Sell pepe #" transactions

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#18]
# Both sell and cosy time auction are "Start sale auction: Sell pepe #" transactions

*Insert brief issue description*
![image](https://user-images.githubusercontent.com/7458738/41287698-e12035f0-6e43-11e8-86a3-37929cf1ed27.png)

Both sell and cosy time auction are "Start sale auction: Sell pepe #" transactions.
in-site wallet shows up the same for diffrent actions.

**Comment by crmn111** [comment]
![pepedapp](https://user-images.githubusercontent.com/881181/41287936-bf924260-6e44-11e8-99d3-b89b0bcbda65.png)

**Comment by programmerror** [comment]
Turned out the event name was sourced incorrectly, due to an ID comparison being wrong. It is fixed in the next release :+1:
