### ISSUE TITLE
Selling pepe for negative amount

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#19]
# Selling pepe for negative amount.

![image](https://user-images.githubusercontent.com/7458738/41287837-591a379a-6e44-11e8-8671-668f66e040df.png)

selling pepe for negative amount. 
https://ropsten.etherscan.io//tx/0x61f2482716125374193db36b2f58130b88c8e9917f88570a69f1dcbb40e34a69

Results in pepe being listed for something like "115792089237316195423570985008687907853269984665640564039456.588498653870380676"
when clicked this pepe is not for sale.

https://dev.cryptopepes.io/pepe/75

This pepe's page also turned invisable for me.
![image](https://user-images.githubusercontent.com/7458738/41287954-cdf4d14c-6e44-11e8-8c77-d05106e54afb.png)

Empty body on element inspect. 

W10 chrome.

**Comment by programmerror** [comment]
Fixed in next release, the number wasn't recognized as a Big-number correctly, which made it by-pass the negativity check.
