### ISSUE TITLE
pepe stuck after hop auction.

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#22]
# pepe stuck after hop.

pepe 104 got stuck after being auctioned off and someone trying to hop with it.
its not stuck in "wants to hop - active" 
![image](https://user-images.githubusercontent.com/7458738/41293962-1c55b81c-6e57-11e8-86b9-f55ebfb9ce6b.png)

there is no price eiter. going to the page there is a button. "retrieve from auction"
making an invalid meta-mask popup. 
![image](https://user-images.githubusercontent.com/7458738/41294006-3ba2908c-6e57-11e8-9e05-35b573846b65.png)

### Accounts used

0x892b85B5a6412e12E749A94D3e0b9fe519C4a032

### Common questions

> Check the boxes that apply

- [x] Logged in?
- [ ] Recently switched accounts?
- [ ] Do you use multiple accounts at the same time?

> Answer briefly, if relevant

**Which Web3 wallet do you use?**

Metamask, w10 chrome

### Steps to reproduce

1. set for hop.
2. someone hops. something goes wrong
3. pepestuck

**Comment by rayhvh** [comment]
![image](https://user-images.githubusercontent.com/7458738/41305864-828cf3f8-6e74-11e8-9691-eba896fedb95.png)
pepe stuck after normal auction

**Comment by programmerror** [comment]
It got unstuck after a scheduled backfill, don't know why the watching service didn't pick up on it. It's bad, but nothing was lost, and it recovered itself without intervention. Overall good to see the backup service working nicely. Good report, will investigate further :+1:

**Comment by programmerror** [comment]
The UX aspect is part of the feedback problem, as described in #30. The pepe got unstuck, so I'm not blaming the current system, it's just not as quick in giving feedback. You can follow this issue further in #30
