### ISSUE TITLE
Reddit link goes to wrong page

### ISSUE THREAD

**Issue by kitblake** [CryptoPepes/cryptopepes-alpha-test#23]
# Reddit link goes to wrong page

Goes to a page we don't control:
https://reddit.com/r/cryptopepes
Should go to:
https://reddit.com/r/cryptopepe
### Affected parts

- [ ] Backend API: search/lookups
- [ ] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [ ] Miscellaneous

**Comment by programmerror** [comment]
fixed, thanks for sharing
