### ISSUE TITLE
About the breeding slideup

### ISSUE THREAD

**Issue by kitblake** [CryptoPepes/cryptopepes-alpha-test#26]
# About the breeding slideup

When you pick a Mother and a Father the 'breeding slideup' appears. For the uninitiated, it's not clear what this is. Of course, the "Start cozy time ❤️" button below is a clue. 

1. Would be good to give the slideup a heading, either top left or centered, such as:
Cozy Time Plans
Cozy Time
Get Cozy
Go Cozy

2. At the same time it would be better if the "✖️Close" button was top right. 

3. Lastly, if you close the slideup without doing anything, you can't get it back. Only by deselecting and reselecting a parent will it slide up again. 
After closing the slideup, either by clicking the X or clicking outside of it, the parents stay selected. Maybe we need a "Go Cozy" button under the Pepes that becomes visible when two parents are selected. 

### Affected parts

- [x] Frontend: Visual
- [x] Frontend: interactions

**Comment by kitblake** [comment]
Ah, in the header there's an icon for "Show cozy time plans" so that invalidates point #3.

**Comment by programmerror** [comment]
Added a "show cozy plans" menu option to the cozy selection menu, for easy accessibility. Included in next release :+1:
