### ISSUE TITLE
Typo on the mainpage

### ISSUE THREAD

**Issue by Twente-Mining** [CryptoPepes/cryptopepes-alpha-test#27]
Typo's on the mainpage
Crypto pepes instead of Cryptopepes

### Affected parts
- [x ] Frontend: Visual

![cpep](https://user-images.githubusercontent.com/34941290/41317445-7e4280a8-6e95-11e8-86ca-410bf8bd4b06.PNG)

![cpep2](https://user-images.githubusercontent.com/34941290/41317496-a3b1e482-6e95-11e8-955c-d1bdff1fb507.PNG)

![cpep3](https://user-images.githubusercontent.com/34941290/41317548-cddd7e56-6e95-11e8-9aad-eb19881bfaea.PNG)

![cpep4](https://user-images.githubusercontent.com/34941290/41317589-eb484ebc-6e95-11e8-97de-7bd0fd5e0f3c.PNG)

**Comment by Twente-Mining** [comment]
another 2 on the about page
 
![cpep5](https://user-images.githubusercontent.com/34941290/41317805-9a46fc2e-6e96-11e8-9e20-615459d6f8ca.PNG)

**Comment by programmerror** [comment]
Fixed in next release
