### ISSUE TITLE
Uncaught promise - TypeError: _.isDescending is not a function

### ISSUE THREAD

**Issue by krznbtni** [CryptoPepes/cryptopepes-alpha-test#28]
# Uncaught promise - TypeError: _.isDescending is not a function

I bought two Pepes and was about to breed one of them when I got the error: `Uncaught promise - TypeError: _.isDescending is not a function`.

### Affected parts

- [ ] Backend API: search/lookups
- [x] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [ ] Miscellaneous

### Accounts used

> Please name the accounts used, for better communication.

```
Main: 0x7Ac0c1149E1DE2273Ae571e3B6a0a392CFe05368
Test receiver: 0x7Ac0c1149E1DE2273Ae571e3B6a0a392CFe05368
```

### Common questions

> Check the boxes that apply

- [x] Logged in?
- [ ] Recently switched accounts?
- [ ] Do you use multiple accounts at the same time?

> Answer briefly, if relevant

**Which Web3 wallet do you use?**

MetaMask

### Steps to reproduce

1. Bought a Pepe
2. Selected one to breed with
3. Pressed start to breed

### Data

> Note, if possible, see if you can collect data such as browser log.
```
VM80 client.js:95 Uncaught (in promise) TypeError: _.isDescending is not a function
    at t.value (VM80 client.js:95)
    at m (VM80 client.js:62)
    at beginWork (VM80 client.js:62)
    at a (VM80 client.js:62)
    at i (VM80 client.js:62)
    at M (VM80 client.js:62)
    at b (VM80 client.js:62)
    at C (VM80 client.js:62)
    at h (VM80 client.js:62)
    at c (VM80 client.js:62)
```

**Comment by programmerror** [comment]
Thanks for the clear bug report. The issue has been identified; it happens when a pepe is de-serialized from local storage; properties are re-instated, but functions are not. This will be fixed in the next release :+1:
