### ISSUE TITLE
Attempting to breed before Cooldown results in a Metamask error 

### ISSUE THREAD

**Issue by kitblake** [CryptoPepes/cryptopepes-alpha-test#29]
# Attempting to breed before Cooldown results in a Metamask error 

When breeding the same two Pepes immediately after breeding them before, there should be feedback about the Cooldown period in the app. Instead the eager breeder sees an error in Metamask:
"Transaction Error. Exception thrown in contract code."

### Affected parts

- [ ] Backend API: search/lookups
- [ ] Frontend: Visual
- [x] Frontend: interactions
- [x] Smartcontract: CPEP erc721
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous

### Accounts used

```
Main: 0xEcFf9b352fbb9A59aEAe10D6DAd636e6f07a0570
```
### Common questions

- [x] Logged in?
- [x] Do you use multiple accounts at the same time?

**Which Web3 wallet do you use?**

Metamask

### Steps to reproduce

1. Breed two Pepes
2. Breed them again within a few minutes
3. Results in an error in Metamask

**Comment by programmerror** [comment]
A cooldown check will be added to the dialog next release :+1:

**Comment by kitblake** [comment]
This issue is back, as of this afternoon. This morning it was fixed; I tried mating a hot father and mother and got two red warning boxes in the overlay dialog. But now I get the Mm error again: "Transaction Error. Exception thrown in contract code."

**Comment by kitblake** [comment]
Today the warning is working again.
