### ISSUE TITLE
Bio-text not matching

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#3]
# non matching bio text

Bio text on pepe 140, 
"Whats in the bag? IM SO EXTRA. EVERYTHING I DO, I DO IN CAPSLOCK. I am here to show everyone I use apple. back in 1960. Do you like my hair? Later I plan to pay Bitgrail back. Nobody cares..."
does not really match

### Affected parts

- [ ] Backend API: search/lookups
- [x] Frontend: Visual
- [ ] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [x] Miscellaneous

### Steps to reproduce

https://dev.cryptopepes.io/pepe/140

**Comment by programmerror** [comment]
The text is an experiment, and is yet to be improved. If you want, you can help writing better/new parts, and share them on telegram.
