### ISSUE TITLE
Unable to buy Cryptopepe

### ISSUE THREAD

**Issue by Twente-Mining** [CryptoPepes/cryptopepes-alpha-test#31]
Unable to buy Cryptopepe that is currently listed as "for sale" 

### Affected parts

- [ ] Backend API: search/lookups
- [x] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [x] Miscellaneous

![image](https://user-images.githubusercontent.com/34941290/41434329-a756aafa-701b-11e8-81b3-387261b23f18.png)
![image](https://user-images.githubusercontent.com/34941290/41434337-b00f4bf2-701b-11e8-9f66-a3204fb3aa8f.png)

**Comment by programmerror** [comment]
Fixed a problem in the backend; frontend was showing the correct data, but the backend wasn't able to update the datastore backing the query system.
