### ISSUE TITLE
Dropdown background 

### ISSUE THREAD

**Issue by Twente-Mining** [CryptoPepes/cryptopepes-alpha-test#33]
Dropdown background incorrect in dark theme
This is for the "sorting" dropdown menu

- [ x] Frontend: Visual

The issue is there at all 3 categories:
*All Pepes

![image](https://user-images.githubusercontent.com/34941290/41502862-0da517f2-71c4-11e8-8ff2-a8549071c370.png)

*For Sale

![image](https://user-images.githubusercontent.com/34941290/41502869-32b351a8-71c4-11e8-9b58-a10f3376d85e.png)

*Wants to hop

![image](https://user-images.githubusercontent.com/34941290/41502870-3b69f932-71c4-11e8-8c3d-9e38cf8c6c6d.png)

**Comment by programmerror** [comment]
Forgot to close the issue, this was fixed in the last release
