### ISSUE TITLE
Use points instead of comma's as decimal sign

### ISSUE THREAD

**Issue by crmn111** [CryptoPepes/cryptopepes-alpha-test#5]
Use points instead of comma's as decimal sign in pepe auction

### Affected parts

sell pepe auction

**Which Web3 wallet do you use?**

Metamask

<img width="630" alt="screen shot 2018-06-12 at 11 42 26" src="https://user-images.githubusercontent.com/881181/41283001-beb3e81c-6e35-11e8-90c8-7d88baf15c1f.png">

**Comment by pesla** [comment]
Instead, use an `Intl` to get the decimal separator for the locale of the user (eg. [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat)).

**Comment by programmerror** [comment]
This is a mistake on your end. It looks like it already uses localized separators. I get an "invalid price" warning when using commas, and dot works as expected.

**Comment by crmn111** [comment]
Dot works as expected but the User Interface shows comma's.

**Comment by programmerror** [comment]
The comma in the formatting don't show up for me, it's a localization thing, dependent on the language of your browser. Users can just change their preference if they prefer dots, which seems like a reasonable solution.
