### ISSUE TITLE
different pepe image size. 

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#6]
# 

### Affected parts

- [ ] Backend API: search/lookups
- [x] Frontend: Visual
- [ ] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [ ] Miscellaneous

### big.
![image](https://user-images.githubusercontent.com/7458738/41282684-fcc19ab0-6e34-11e8-8627-a0cd064951d8.png)
### smoll
![image](https://user-images.githubusercontent.com/7458738/41282695-062d7344-6e35-11e8-8dd1-0cf8783f073c.png)

**Comment by programmerror** [comment]
Strange visual issue you've here, will try to fix it together with the name length issue.

**Comment by programmerror** [comment]
fixed
