### ISSUE TITLE
Unsuccessful bids not tracked, Auction loser gets no feedback

### ISSUE THREAD

**Issue by Twente-Mining** [CryptoPepes/cryptopepes-alpha-test#7]
Unsuccessful bids/ bids that are overbid are not tracked, Auction loser gets no feedback 

### Affected parts

- [x] Backend API: search/lookups
- [x] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [ ] Miscellaneous

### Common questions

> Check the boxes that apply

- [x] Logged in?

**Comment by programmerror** [comment]
Seeing this as part of a larger issue, so I created #30. You can continue discussion there if you want. Closing this issue now.
