### ISSUE TITLE
Owner username not showing up.

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#8]
# username owner not showing on pepe. page

I've set my username way before i bought the pepe. and noticed its not being shown.

### Accounts used
0x892b85B5a6412e12E749A94D3e0b9fe519C4a032

### Common questions

> Check the boxes that apply

- [x] Logged in?
- [ ] Recently switched accounts?
- [ ] Do you use multiple accounts at the same time?

> Answer briefly, if relevant

**Which Web3 wallet do you use?**

Metamask, 

### Steps to reproduce

1. have username
2. buy pepe
3. no username as owner.

![image](https://user-images.githubusercontent.com/7458738/41283146-20df9b26-6e36-11e8-8305-62f07ffef570.png)

**Comment by programmerror** [comment]
Portfolio and wallet show it right, but the detail page doesn't. Good spot. Should be easy to fix. :+1:

**Comment by programmerror** [comment]
Fixed it, was due to a property update (address initially being unknown). Fix rolls out in next deploy.
